### ISSUE TITLE
Checkbox labels should be inline with the related checkbox

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-style#80] opened 2016-06-07 20:11 UTC
Bringing over issue 18f/cg-deck#304 to track in this repo. Currently, checkboxes and their labels are on separate lines. For easier context and a better UI, we want them to be inline by default.

Acceptance criteria:
- [ ] The `<label>` should be on the same line and visual connected to the checkbox that controls it.

Screenshot:
![Screenshot of block checkboxes and labels](https://cloud.githubusercontent.com/assets/1701077/15789412/f4fb4772-2980-11e6-99dc-43fd1023a1a9.png)

**Comment by msecret** [comment] 2016-06-08 19:09
This sounds like a duplicate of #304, should we close?

**Closed as completed** 2016-06-08 20:28 UTC
